import type { Metadata } from 'next'
import { gloriaHallelujah } from './ui/fonts'
import './globals.css'
import { ReadingListProvider } from './contexts/ReadingListContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>): JSX.Element {
  return (
    <html lang="en">
      <body className={`${gloriaHallelujah.className} text-white`}>
        <header></header>
        <ReadingListProvider>
         {children}
        </ReadingListProvider>
      </body>
    </html>
  )
}
